"use client";

import type { RefObject } from "react";
import type { ShopSettings, CargoShipment } from "@/types";
import InvoiceQRCode from "@/components/invoice/InvoiceQRCode";

interface CargoShipmentLabelTemplateProps {
  ref: RefObject<HTMLDivElement | null>;
  shop: ShopSettings | null;
  shipment: Pick<CargoShipment, "cargoNo" | "carrierName" | "carrierPhone" | "flightNumber" | "status">;
  orderDisplayId: string | null;
  categoryNames: string[];
  totalWeight: number;
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", gap: 16, padding: "10px 0", borderTop: "1px solid #eef2f6" }}>
      <span style={{ fontSize: 12, color: "#64748b", whiteSpace: "nowrap" }}>{label}</span>
      <span style={{ fontSize: 13, fontWeight: 600, color: "#0f172a", textAlign: "right", maxWidth: 300 }}>{value}</span>
    </div>
  );
}

function statusLabel(s: string) {
  return s.split("_").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

export function CargoShipmentLabelTemplate({
  ref,
  shop,
  shipment,
  orderDisplayId,
  categoryNames,
  totalWeight,
}: CargoShipmentLabelTemplateProps) {
  return (
    <div
      ref={ref}
      style={{
        width: "520px",
        fontFamily: "Arial, Helvetica, sans-serif",
        position: "fixed",
        left: "-9999px",
        top: "-9999px",
        background: "#f4f5f7",
        color: "#1e293b",
        boxSizing: "border-box",
      }}
    >
      {/* ── Header bar ── */}
      <div style={{ background: "linear-gradient(120deg, #1d4ed8, #0891b2)", padding: "22px 32px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          {shop?.logoUrl && (
            <img src={shop.logoUrl} alt="logo" style={{ width: 32, height: 32, objectFit: "contain", borderRadius: 6 }} />
          )}
          <span style={{ color: "white", fontSize: 15, fontWeight: 700 }}>{shop?.shopName ?? "Sine Shin Manager"}</span>
        </div>
        <span style={{ background: "rgba(255,255,255,0.16)", color: "white", borderRadius: 9999, padding: "5px 14px", fontSize: 11, textTransform: "uppercase", fontWeight: 700, letterSpacing: "0.12em" }}>
          Shipment Label
        </span>
      </div>

      <div style={{ padding: "28px 32px 32px" }}>
        {/* ── Cargo number block ── */}
        <p style={{ fontSize: 11, fontWeight: 700, color: "#94a3b8", textTransform: "uppercase", letterSpacing: "0.16em", margin: "0 0 8px" }}>
          Cargo No
        </p>
        <p style={{ fontSize: 30, fontWeight: 800, color: "#0f172a", margin: "0 0 14px", lineHeight: 1.15, fontFamily: "monospace" }}>
          {shipment.cargoNo}
        </p>

        <div style={{ background: "white", borderRadius: 18, border: "1px solid #e2e8f0", padding: "6px 20px", marginBottom: 20 }}>
          {orderDisplayId && <InfoRow label="Order No" value={orderDisplayId} />}
          {shipment.carrierName && <InfoRow label="Carrier" value={shipment.carrierName} />}
          {shipment.carrierPhone && <InfoRow label="Carrier Phone" value={shipment.carrierPhone} />}
          {shipment.flightNumber && <InfoRow label="Flight No" value={shipment.flightNumber} />}
          {categoryNames.length > 0 && <InfoRow label="Category" value={categoryNames.join(", ")} />}
          <InfoRow label="Total Weight" value={`${totalWeight.toFixed(2)} kg`} />
          <InfoRow label="Status" value={statusLabel(shipment.status)} />
        </div>

        {/* ── QR + footer ── */}
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", borderTop: "1px dashed #cbd5e1", paddingTop: 20 }}>
          <div>
            <p style={{ margin: 0, fontSize: 12, color: "#64748b" }}>Generated by</p>
            <p style={{ margin: "2px 0 0", fontSize: 13, fontWeight: 700, color: "#0f172a" }}>{shop?.shopName ?? "Sine Shin Manager"}</p>
          </div>
          <InvoiceQRCode
            data={{
              orderId: shipment.cargoNo,
              customer: { name: orderDisplayId, phone: shipment.carrierPhone },
            }}
            size={88}
          />
        </div>
      </div>
    </div>
  );
}
